use_frameworks!

target 'CGSegmentBar_Example' do
  pod 'CGSegmentBar', :path => '../'

  target 'CGSegmentBar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
